// Code generated by "stringer -type=Category -trimprefix=Category"; DO NOT EDIT.

package abuseipdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CategoryDNSCompromise-1]
	_ = x[CategoryDNSPoisoning-2]
	_ = x[CategoryFraudOrders-3]
	_ = x[CategoryDDoSAttack-4]
	_ = x[CategoryFTPBruteForce-5]
	_ = x[CategoryPingOfDeath-6]
	_ = x[CategoryPhishing-7]
	_ = x[CategoryFraudVOIP-8]
	_ = x[CategoryOpenProxy-9]
	_ = x[CategoryWebSpam-10]
	_ = x[CategoryEmailSpam-11]
	_ = x[CategoryBlogSpam-12]
	_ = x[CategoryVPNIP-13]
	_ = x[CategoryPortScan-14]
	_ = x[CategoryHacking-15]
	_ = x[CategorySQLInjection-16]
	_ = x[CategorySpoofing-17]
	_ = x[CategoryBruteForce-18]
	_ = x[CategoryBadWebBot-19]
	_ = x[CategoryExploitedHost-20]
	_ = x[CategoryWebAppAttack-21]
	_ = x[CategorySSH-22]
	_ = x[CategoryIoTTargeted-23]
}

const _Category_name = "DNSCompromiseDNSPoisoningFraudOrdersDDoSAttackFTPBruteForcePingOfDeathPhishingFraudVOIPOpenProxyWebSpamEmailSpamBlogSpamVPNIPPortScanHackingSQLInjectionSpoofingBruteForceBadWebBotExploitedHostWebAppAttackSSHIoTTargeted"

var _Category_index = [...]uint8{0, 13, 25, 36, 46, 59, 70, 78, 87, 96, 103, 112, 120, 125, 133, 140, 152, 160, 170, 179, 192, 204, 207, 218}

func (i Category) String() string {
	i -= 1
	if i < 0 || i >= Category(len(_Category_index)-1) {
		return "Category(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Category_name[_Category_index[i]:_Category_index[i+1]]
}
